development:
  base_url: "https://api.example.com"
  headers:
    Content-Type: "application/json"
    Authorization: "Bearer YOUR_API_TOKEN_HERE"
  timeout: 30

production:
  base_url: "https://api.example.com"
  headers:
    Content-Type: "application/json"
    Authorization: "Bearer YOUR_API_TOKEN_HERE"
  timeout: 30
